### PR TITLE
implemented adblock

### PR DESCRIPTION
**Pull request by UnbreakCode**
Adblock with comments implemented as an explanation for someone

### CODE REVIEW

**Comment by TheLajuj** [comment]
ad block works great 👍

**Comment by PurpX** [comment]
how do i use it? how do i build the exe from the code

**Comment by Luzefiru** [comment]
> how do i use it? how do i build the exe from the code

They used [electron-builder](https://www.electron.build/) according to the README's [credits](https://github.com/richardhbtz/soundcloud-rpc?tab=readme-ov-file#credits).

**Comment by PurpX** [comment]
> > how do i use it? how do i build the exe from the code
> 
> They used [electron-builder](https://www.electron.build/) according to the README's [credits](https://github.com/richardhbtz/soundcloud-rpc?tab=readme-ov-file#credits).

ive spent like 3 hours trying to figure out how to build it using electron builder LOL can i please have some help

**Comment by UnbreakCode** [comment]
> > > how do i use it? how do i build the exe from the code
> > 
> > 
> > They used [electron-builder](https://www.electron.build/) according to the README's [credits](https://github.com/richardhbtz/soundcloud-rpc?tab=readme-ov-file#credits).
> 
> ive spent like 3 hours trying to figure out how to build it using electron builder LOL can i please have some help

install nodejs, do `npm i` in projects folder and run `npm run dist-win`

**Comment by PurpX** [comment]
> > > > how do i use it? how do i build the exe from the code
> > > 
> > > 
> > > They used [electron-builder](https://www.electron.build/) according to the README's [credits](https://github.com/richardhbtz/soundcloud-rpc?tab=readme-ov-file#credits).
> > 
> > 
> > ive spent like 3 hours trying to figure out how to build it using electron builder LOL can i please have some help
> 
> install nodejs, do `npm i` in projects folder and run `npm run dist-win`

im getting an error, yes i tried installing typescript and here is the following attempts

npm i + npm run dist-win: https://imgur.com/a/xTtl3Yx
npm i typescript: https://imgur.com/a/E0h98Vx

sorry if im making a basic mistake im just not to competent with this

**Comment by UnbreakCode** [comment]
> > > > > how do i use it? how do i build the exe from the code
> > > > 
> > > > 
> > > > They used [electron-builder](https://www.electron.build/) according to the README's [credits](https://github.com/richardhbtz/soundcloud-rpc?tab=readme-ov-file#credits).
> > > 
> > > 
> > > ive spent like 3 hours trying to figure out how to build it using electron builder LOL can i please have some help
> > 
> > 
> > install nodejs, do `npm i` in projects folder and run `npm run dist-win`
> 
> im getting an error, yes i tried installing typescript and here is the following attempts
> 
> npm i + npm run dist-win: https://imgur.com/a/xTtl3Yx npm i typescript: https://imgur.com/a/E0h98Vx
> 
> sorry if im making a basic mistake im just not to competent with this

typescript should be installed for this project while executing `npm i`...
Did you checked the node_modules folder if it contains a typescript folder? And did you tried to restart the cmd? You could also try to install it globally using `npm install typescript -g`

**Comment by odiplol** [comment]
this would be awesome, hope this gets merged!

**Pull request merged**
